# Generated by Django 4.2.6 on 2023-11-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bowtie_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emu',
            name='bowties',
            field=models.ManyToManyField(to='main_app.bowtie'),
        ),
    ]
